apiVersion: v1
kind: Pod
metadata:
  name: super-duper-pod
  namespace: homework
  labels:
    app: otus-homework
spec:
  containers:
  - name: nginx-app
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-volume
      mountPath: /homework
    - name: nginx-config-volume
      mountPath: /etc/nginx
      readOnly: true
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  initContainers:
  - name: init
    image: busybox
    command: ["/bin/sh", "-c", "echo 'I love OTUS' > /init/index.html"]
    volumeMounts:
    - name: shared-volume
      mountPath: /init
  volumes:
  - name: shared-volume
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  terminationGracePeriodSeconds: 1
  dnsPolicy: Default